In [31]:
import pickle
import numpy
import matplotlib.pyplot as plt
import sys
sys.path.append("../tools/")
from feature_format import featureFormat, targetFeatureSplit

In [32]:
def Draw(pred, features, poi, mark_poi=False, name="image.png", f1_name="feature 1", f2_name="feature 2"):
    """ some plotting code designed to help you visualize your clusters """

    ### plot each cluster with a different color--add more colors for
    ### drawing more than five clusters
    colors = ["b", "c", "k", "m", "g"]
    for ii, pp in enumerate(pred):
        plt.scatter(features[ii][0], features[ii][1], color = colors[pred[ii]])

    ### if you like, place red stars over points that are POIs (just for funsies)
    if mark_poi:
        for ii, pp in enumerate(pred):
            if poi[ii]:
                plt.scatter(features[ii][0], features[ii][1], color="r", marker="*")
    plt.xlabel(f1_name)
    plt.ylabel(f2_name)
    plt.savefig(name)
    plt.show()


In [33]:
### load in the dict of dicts containing all the data on each person in the dataset
data_dict = pickle.load( open("../final_project/final_project_dataset.pkl", "r") )
### there's an outlier--remove it! 
data_dict.pop("TOTAL", 0)

{'bonus': 97343619,
 'deferral_payments': 32083396,
 'deferred_income': -27992891,
 'director_fees': 1398517,
 'email_address': 'NaN',
 'exercised_stock_options': 311764000,
 'expenses': 5235198,
 'from_messages': 'NaN',
 'from_poi_to_this_person': 'NaN',
 'from_this_person_to_poi': 'NaN',
 'loan_advances': 83925000,
 'long_term_incentive': 48521928,
 'other': 42667589,
 'poi': False,
 'restricted_stock': 130322299,
 'restricted_stock_deferred': -7576788,
 'salary': 26704229,
 'shared_receipt_with_poi': 'NaN',
 'to_messages': 'NaN',
 'total_payments': 309886585,
 'total_stock_value': 434509511}

In [43]:
### the input features we want to use 
### can be any key in the person-level dictionary (salary, director_fees, etc.) 

from sklearn import preprocessing


feature_1 = "salary"
feature_2 = "exercised_stock_options"
feature_3 = "total_payments"
poi  = "poi"
features_list = [poi, feature_1, feature_2, feature_3]
data = featureFormat(data_dict, features_list )
poi, finance_features = targetFeatureSplit( data )

min_max_scaler = preprocessing.MinMaxScaler()
finance_features = min_max_scaler.fit_transform(finance_features)

In [44]:
### in the "clustering with 3 features" part of the mini-project,
### you'll want to change this line to 
### for f1, f2, _ in finance_features:
### (as it's currently written, the line below assumes 2 features)
for f1, f2, _ in finance_features:
    plt.scatter( f1, f2 )
plt.show()

In [45]:
### cluster here; create predictions of the cluster labels
### for the data and store them to a list called pred

from sklearn import cluster

k_means = cluster.KMeans(n_clusters=2)
pred = k_means.fit_predict(finance_features)

In [46]:
### rename the "name" parameter when you change the number of features
### so that the figure gets saved to a different file
try:
    Draw(pred, finance_features, poi, mark_poi=False, name="clusters.pdf", f1_name=feature_1, f2_name=feature_2)
except NameError:
    print "no predictions object named pred found, no clusters to plot"

In [47]:
from operator import itemgetter
sorted(finance_features, key=itemgetter(0))

[array([ 0.       ,  0.0189776,  0.       ]),
 array([ 0.        ,  0.01436717,  0.01784696]),
 array([ 0.        ,  0.15169765,  0.03024205]),
 array([ 0.        ,  0.06458164,  0.00933299]),
 array([ 0.        ,  0.01083617,  0.        ]),
 array([ 0.        ,  0.02999643,  0.00084405]),
 array([  0.00000000e+00,   9.56376871e-05,   9.89766366e-04]),
 array([ 0.        ,  0.        ,  0.00183066]),
 array([ 0.        ,  0.        ,  0.00220796]),
 array([ 0.        ,  0.00287402,  0.        ]),
 array([  0.00000000e+00,   0.00000000e+00,   4.58672218e-06]),
 array([  0.00000000e+00,   0.00000000e+00,   1.42912607e-06]),
 array([ 0.        ,  0.02476032,  0.        ]),
 array([  0.00000000e+00,   0.00000000e+00,   7.68734638e-05]),
 array([ 0.        ,  0.01934225,  0.        ]),
 array([ 0.        ,  0.        ,  0.00205747]),
 array([ 0.        ,  0.01082293,  0.00074828]),
 array([ 0.        ,  0.0120203 ,  0.00084485]),
 array([ 0.        ,  0.00405055,  0.        ]),
 array([  0.

In [50]:
min_max_scaler.transform([200000, 1000000, 0])

/Users/ejm/anaconda2/lib/python2.7/site-packages/sklearn/preprocessing/data.py:359: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


array([ 0.17997621,  0.02911345,  0.        ])